# -*- coding: utf-8 -*-
"""DataType Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6BgIy3UHlYzRBmBKQ3HhW-fDIaAPXSZ
"""

'''
1. Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.
	Given List:
	list1 = ["M", "na", "i", "Ra"]
	list2 = ["y", "me", "s", "hul"]
	Output: [['M','y'], ['na', me'], ['i', 's'], ['Ra', 'hul']]
'''
list1 = ["M", "na", "i", "Ra"]
list2 = ["y", "me", "s", "hul"]
list3=[]
index_wise=list(zip(list1,list2))
for i in index_wise:
  item=list(i)
  list3.append(item)
print(list3)

#---using list comprehension
list3=[list(i) for i in zip(list1,list2)]
print(list3)

'''
2. Write a program to add item 7000 after 6000 in the following Python List
	list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
	Output: [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
'''
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
print(list1)

'''
3. Suppose you are given a list of candy and another list of same size representing no of items of respective candy.
	i.e -
	candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
	no_of_items = [10,20,34,74,32]
	Write a program to show no. of items of each candy type.
	Output:
	Jelly Belly-10
	Kit Kat-20
	Double Bubble-34
	Milky Way-74
	Three Musketeers-32
	'''
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
add=zip(candy_list,no_of_items)
for i in add:
  print(i[0],'-',i[1])

'''
4. Running Sum on list Write a program to print a list after performing running sum on it.
	i.e:
	Input: list1 = [1,2,3,4,5,6]
	Output: [1,3,6,10,15,21]
'''
list1 = [1,2,3,4,5,6]
sum=0
list2=[]
for i in list1:
  sum=sum+i
  list2.append(sum)
print(list2)

'''
5. You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater
and itself.
	i.e. Say given list is [2,4,6,10,1] resultant list will be [22,20,10,23].
	For 1st element 2 ->> these are greater (4+6+10) values and 2 itself so on adding becomes 22.
	For 2nd element 4 ->> greater elements are (6, 10) and 4 itself, so on adding 20
	like wise for all other elememts.
	[2,4,6,10,1]-->[22,20,16,10,23]
'''
list1=[2,4,6,10,1]
list2=[]
sum=0
for i in list1:
  sum=i
  for j in list1:
    if i<j:
      sum=sum+j
  list2.append(sum)
print(list2)

'''
6. Find list of common unique items from two list. and show in increasing order
	Input:
	num1 = [23,45,67,78,89,34]
	num2 = [34,89,55,56,39,67]
	Output: [34, 67, 89]
'''
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
num3=[]
for i in num1:
    if i in num2:
        num3.append(i)
num3.sort()
print(num3)

'''
7. Sort a list of alphanumeric strings based on product value of numeric character in it.
If in any string there is no numeric character take it's product value as 1.
	Input: ['1ac21', '23fg', '456', '098d','1','kls']
	Output: ['456', '23fg', '1ac21', '1', 'kls', '098d']
'''
def product_of_digits(s):
    prod = 1
    has_digit = False
    for ch in s:
        if ch.isdigit():
            has_digit = True
            prod *= int(ch)
    return prod if has_digit else 1
data = ['1ac21', '23fg', '456', '098d', '1', 'kls']
result = sorted(data, key=product_of_digits, reverse=True)
print(result)

#---using math
import math
def product_of_digits(s):
    digits = [int(ch) for ch in s if ch.isdigit()]
    if digits:
      return math.prod(digits)
    else:
       return 1
data = ['1ac21', '23fg', '456', '098d', '1', 'kls']
result = sorted(data, key=product_of_digits, reverse=True)
print(result)

'''
8. Write a program that can find the max number of each row of a matrix
	Example:
	Input: [[1,2,3],[4,5,6],[7,8,9]]
	Output: [3,6,9]
'''
list=[[1,2,3],[4,5,6],[7,8,9]]
list1=[]
for i in list:
    no=max(i)
    list1.append(no)
print(list1)

#---using list comprehension
no=[max(i) for i in list]
print(no)

'''
9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record.
Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.
Show every students record in form of tuples if matches all required criteria.It is assumed that there will be only one primry skill.
If no such candidate found, print No such candidate
	Input:
	Enter No of records- 2
	Enter Details of student-1
	Enter Student name- Manohar
	Enter Higher Education- B.Tech
	Enter Primary Skill- Python
	Enter Year of Graduation- 2022
	Enter Details of student-2
	Enter Student name- Ponian
	Enter Higher Education- B.Sc.
	Enter Primary Skill- C++
	Enter Year of Graduation- 2020

	Enter Job Role Requirement
	Enter Skill- Python
	Enter Higher Education- B.Tech
	Enter Year of Graduation- 2022
	Output: ('Manohar', 'B.tech', 'Python', '2022')
'''
no = int(input('Enter no of records: '))
records = ()
for i in range(no):
    print(f"\nEnter Details of student - {i+1}")
    nm = input('Enter Student name- ')
    edu = input('Enter Higher Education- ')
    sk = input('Enter Primary Skill- ')
    yr = input('Enter Year of Graduation- ')
    stud = (nm, edu, sk, yr)
    records += (stud,)   # nested tuple
print("\nEnter Job Role Requirement")
req_sk = input('Enter Skill- ')
req_edu = input('Enter Higher Education- ')
req_yr = input('Enter Year of Graduation- ')
found = False
for stud in records:
    if stud[2] == req_sk and stud[1] == req_edu and stud[3] == req_yr:
        print(stud)
        found = True
if not found:
    print("No such candidate")

'''
10. Write a program to find set of common elements in three lists using sets.
	Input : ar1 = [1, 5, 10, 20, 40, 80]
			ar2 = [6, 7, 20, 80, 100]
			ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
	Output : [80, 20]
'''
ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
result=set(ar1) & set(ar2) & set(ar3)
#print(list(result)) #'list' object is not callable
list3=[]
for i in result:
  list3.append(i)
print(list3)

'''
11. Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.
	Input:
	Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
	Output: No of unique vowels-6
'''
str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
s=set(str1)
cnt=0
for i in s:
    if i in 'aeiouAEIOU':
        cnt+=1
print('No of unique vowels -',cnt)

'''
12. Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using list-comprehension.
	Example 1:
	Input:
	lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
	lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
	Output: [9, 10, 4, 5]
'''
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
result = [x for x in lst1 if x in lst2]
print(result)

'''
	Example 2:
	Input:
	lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
	lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
	Output: [9, 11, 26, 28]
'''
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
result = [x for x in lst1 if x in lst2]
print(result)

'''
13. Convert a list of Tuples into Dictionary.
	Example 1:
	Input: [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
	Output: {'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
'''
l=[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
d={}
for i in list:
    d.setdefault(i[0],[]).append(i[1])
print(d)

'''
	Example 2:
	Input: [('A', 1), ('B', 2), ('C', 3)]
	Output: {'A': [1], 'B': [2], 'C': [3]}
'''
l=[('A', 1), ('B', 2), ('C', 3)]
d={}
for i in list:
    d.setdefault(i[0],[]).append(i[1])
print(d)

'''
14. Write a Python function that takes a list and returns a new list with unique elements of the first list.
	Exercise 1:
	Input: [1,2,3,3,3,3,4,5]
	Output: [1, 2, 3, 4, 5]
'''
l=[1,2,3,3,3,3,4,5]
l2=[]
for i in l:
    if i not in l2:
        l2.append(i)
print(l2)

#----using listcomprehension
l3=[]
[l3.append(i) for i in l if i not in l3]
print(l3)

'''
15.  Write a Python program to print the even numbers from a given list.
		Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
		Expected Result : [2, 4, 6, 8]
'''
l=[1, 2, 3, 4, 5, 6, 7, 8, 9]
even=[i for i in l if i%2==0]
print(even)

'''
16. Write a Python function to check whether a number is perfect or not.¶
	A Perfect number is a number that is half the sum of all of its positive divisors (including itself).
	Example :
	The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
	Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

	The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.
'''
def is_prime(n):
    sum=0
    for i in range(1,n):
        if n%i==0:
            sum+=i
    if n==sum:
        print('is prime')
    else:
        print('not prime')
is_prime(496)
is_prime(8128)

'''
17. Write a Python function to concatenate any no of dictionaries to create a new one.
	Sample Dictionary :
	dic1={1:10, 2:20}
	dic2={3:30, 4:40}
	dic3={5:50,6:60}
	Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
'''
def merge_dicts(*dicts):
    result = {}
    for d in dicts:
        result.update(d)
    return result
dic1 = {1:10, 2:20}
dic2 = {3:30, 4:40}
dic3 = {5:50, 6:60}
output = merge_dicts(dic1, dic2, dic3)
print(output)

'''
18. Write a python function that receives a list of integers and prints out a histogram of bin size 10
	Input: [13,42,15,37,22,39,41,50]
	Output: {11-20:2,21-30:1,31-40:2,41-50:3}
'''
def histogram(lst):
    bins = {}
    for num in lst:
        start = (num // 10) * 10 + 1   #13 → (13 // 10 = 1) → 1×10 +1 = 11
        end = start + 9
        key = f"{start}-{end}"         #create a key
        bins[key] = bins.get(key, 0) + 1 #count values
    return dict(sorted(bins.items()))
data = [13,42,15,37,22,39,41,50]
print(histogram(data))