# -*- coding: utf-8 -*-
"""Exception-Handling-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjRfGsZhHBRRFxqXiqjjW9sotAOFpJVp
"""

'''
1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.
'''
try:
    num = int(input("Enter a number: "))
    div = int(input("Enter a number to divide by: "))
    result = num / div
    print("Result:", result)
except ZeroDivisionError:
    print("\nError: Division by zero is not allowed.")

'''
2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer.
'''
try:
    num = int(input("Enter an integer: "))
    print("You entered:", num)
except ValueError:
    print("\nError: Invalid input. Please enter a valid integer.")

'''
3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.
'''
try:
    file_name = input("Enter the file name: ")
    with open(file_name, 'r') as f:
        content = f.read()
        print("File content:")
        print(content)
except FileNotFoundError:
    print("\nError: File not found.")

'''
4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical.
'''
try:
    num1 = int(input("Enter the first number: "))
    num2 = input("Enter the second number: ")
    result = num1 + num2
    print(f'Result: {result}')
except TypeError:
    print("\nError: Invalid input. Please enter numerical values.")

'''
5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.
'''
filename = 'protected_file.txt'
try:
    with open(filename, 'w') as file:
        file.write("Hello, world!")
    print(f"Successfully wrote to '{filename}'")

except PermissionError:
    print(f"Error: Permission denied to open the file '{filename}'.")
    print("You might need to run the script with elevated privileges (e.g., as an administrator) or check file permissions.")

except Exception as e:
    print(f"An unexpected error occurred: {e}")

'''
6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.
'''
try:
    my_list = [1,2,4,5]
    index = int(input("Enter an index: "))
    no=int(input("Enter a no to change: "))
    my_list[index]=no
    print(f"updated list: {my_list}")
except IndexError:
    print("\nError: Index out of range.")

'''
7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.
'''
try:
    result = 1 / 0
except ArithmeticError as e:
    print(f"An arithmetic error occurred: {e}")