# -*- coding: utf-8 -*-
"""File-IO-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10szHip3xl4UKFwQh1U-vtKkwJJCxvyN0
"""

'''
1. Write a Python program to read an entire text file.
'''
fname='sample1.txt'
with open(fname,'w') as f:
  f.write('Hello, Python file handling!\n')
  f.write('This is the second line.\n')
  f.write('And a third line.\n')
  print(f'Successfully wrote in {fname} file')

#read entire data
try:
  with open('sample1.txt','r') as f:
    print(f.read())
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
2. Write a Python program to read first n lines of a file.
'''
try:
    n = int(input("Enter number of lines to read: "))
    with open("sample1.txt", "r") as file:
        for i in range(n):
            line = file.readline()
            if not line:
                break
            print(line, end="")
except FileNotFoundError:
    print("File not found.")
except Exception as e:
    print("Error:", e)

'''
3. Write a Python program to append text to a file and display the text.
'''
try:
  with open('sample1.txt','a') as f:
    f.write('This is the appended line.')
  with open('sample1.txt','r') as f:
    print(f.read())
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
4. Write a Python program to read last n lines of a file.
'''
try:
    n = int(input("Enter number of lines: "))
    with open('sample1.txt', 'r') as file:
        lines = file.readlines()
        last_lines = lines[-n:]   # get last n lines using -ve slicing
        for line in last_lines:
            print(line, end="")
except FileNotFoundError:
    print("Error: File not found")
except Exception as e:
    print("Error:", e)

'''
5. Write a Python program to read a file line by line and store it into a list.
'''
try:
  with open('sample1.txt','r') as f:
    lines=f.readlines()
    print(lines)
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
6. Write a Python program to read a file line by line store it into a variable.
'''
try:
  with open('sample1.txt','r') as f:
    content = f.read()   # stores whole file in one variable
    print(content)
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
7. Write a python program to find the longest words.
'''
#********************
import string
try:
  with open('sample1.txt','r') as f:
    content=f.read()

    #remove punctuation
    clean=''
    for word in content:
      if word not in string.punctuation:
        clean+=word

    #paragraph to list
    words=clean.split()
    max_len = 0

    #find max length
    for word in words:
      if len(word) > max_len:
        max_len = len(word)

     #if multiple words have same size
    longest_words = []
    for word in words:
      if len(word) == max_len:
          longest_words.append(word)
    print("Longest words:", longest_words)
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

#----using sorted()
import string
try:
  with open('sample1.txt','r') as f:
    content=f.read()
    clean=''
    for word in content:
      if word not in string.punctuation:
        clean+=word
    l=clean.split()

    sorted_words = sorted(l, key=len)
    max_len=len(sorted_words[-1])
    longest_words = []
    for word in sorted_words:
        if len(word) == max_len:
            longest_words.append(word)
    print("Longest words:", longest_words)

except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
8. Write a Python program to count the number of lines in a text file.
'''
try:
  count=0
  with open('sample1.txt','r') as f:
    lines=f.readlines()
    for i in lines:
      count+=1
    print(f'no of lines: {count}')
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
9. Write a Python program to count the frequency of words in a file.
'''
#******using for loop
import string
try:
  with open('sample1.txt','r') as f:
    content=f.read()
    clean_content = ""
    for word in content:
      if word not in string.punctuation:
        clean_content += word
    l=clean_content.split()
    for i in set(l):
      print(i,'-',l.count(i))
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)
print()

#----using maketrans
import string
try:
  with open('sample1.txt','r') as f:
    content=f.read()
    translator = str.maketrans('', '', string.punctuation)
    clean_content.translate(translator)
    l=clean_content.split()
    for i in set(l):
      print(i,'-',l.count(i))
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
10. Write a Python program to get the file size of a plain file.
'''
#***************
import os
try:
    size = os.path.getsize('sample1.txt')
    print("File size:", size, "bytes")
except FileNotFoundError:
    print("Error: File not found")
except Exception as e:
    print("Error:", e)

'''
11. Write a Python program to write a list to a file.
'''
try:
  list1=[1,2,3,4,5]
  with open('sample2.txt','w') as f:
    for i in list1:
      f.write(str(i)+'\n')
    print('Successfully wrote in sample2.txt file')
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
12. Write a Python program to copy the contents of a file to another file .
'''
try:
  with open('sample1.txt','r') as f1:
    content=f1.read()
    with open('sample3.txt','w') as f2:
      f2.write(content)
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)

'''
13. Write a Python program to read a random line from a file.
'''
import random
try:
    with open('sample1.txt', 'r') as file:
        lines = file.readlines()
        if lines:
            random_line = random.choice(lines) #Returns a random item from the given sequence
            print("Random line:", random_line.strip())
        else:
            print("File is empty")
except FileNotFoundError:
    print("Error: File not found")
except Exception as e:
    print("Error:", e)

'''
14. Write a Python program to assess if a file is closed or not.
'''
#**********
file = open("sample1.txt", "r")
print("Is file closed?", file.closed)   # False (file is open)
file.close()
print("Is file closed?", file.closed)   # True (file is closed)

'''
15.Write a Python program that takes a text file as input and returns the number of words of a given text file.
'''
#**********
try:
  fname=input('enter a file name:')
  with open(fname,'r') as f:
      content = f.read()
      words = content.split()   # splits by spaces, newline, tabs
      count = len(words)
      print("Number of words:", count)
except FileNotFoundError:
  print('Error: File not found')
except Exception as e:
  print('Error:',e)