# -*- coding: utf-8 -*-
"""Function-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eklbPt17w5j-qrkqbb4KTksCATkyFCkE
"""

'''
1. Write a Python function to find the maximum of three numbers.
'''
def max_no(n1,n2,n3):
    if n1>n2 and n1>n3:
        return n1
    elif n2>n3:
        return n2
    else:
        return n2
print('maximum_no: ',max_no(22,44,11))

'''
2. Write a Python function to sum all the numbers in a list.
	Sample List : (8, 2, 3, 0, 7)
	Expected Output : 20
'''
def sum_element(l):
    sum=0
    for i in l:
        sum+=i
    return sum
l=[8, 2, 3, 0, 7]
print(sum_element(l))

'''
3. Write a Python function to multiply all the numbers in a list.
	Sample List : (8, 2, 3, -1, 7)
	Expected Output : -336
'''
def mul_element(l):
    mul=1
    for i in l:
        mul*=i
    return mul
l=[8, 2, 3, -1, 7]
mul_element(l)

'''
4. Write a Python function to reverse a string.
	Sample String : "1234abcd"
	Expected Output : "dcba4321"
	'''
#---using slicing
def reverse(s):
  rev=s[::-1]
  return rev
s="1234abcd"
print(reverse(s))

#---using reversed
def reverse(s):
  rev=''.join(reversed(s))
  return rev
s="1234abcd"
print(reverse(s))

#---using loop
def reverse(s):
  rev=''
  for i in s:
    rev=i+rev
  return rev
s="1234abcd"
print(reverse(s))

'''
5. Write a Python function to check whether a number falls within a given range.
'''
def check_range(num, start, end):
    if num >= start and num <= end:
        return True
    else:
        return False
check_range(13,11,20)

'''
6. Write a Python function that accepts a string and counts the number of upper and lower case letters.
	Sample String : 'The quick Brow Fox'
	Expected Output :
	No. of Upper case characters : 3
	No. of Lower case Characters : 12
'''
def check_letter(s):
    ucnt=0
    lcnt=0
    for i in s:
        if i.isupper():
            ucnt+=1
        if i.islower():
            lcnt+=1
    print('no. of uppercase character: ',ucnt)
    print('no. of uppercase character: ',lcnt)
s='The quick Brow Fox'
check_letter(s)

'''
7. Write a Python function that takes a list and returns a new list with distinct elements from the first list.
	Sample List : [1,2,3,3,3,3,4,5]
	Unique List : [1, 2, 3, 4, 5]
'''
def unique(l):
  l1=[]
  for i in l:
    if i not in l1:
      l1.append(i)
  return l1
l=[1,2,3,3,3,3,4,5]
print(unique(l))

'''
8. Write a Python function that checks whether a passed string is a palindrome or not.
	Note: A palindrome is a word, phrase, or sequence that reads the same backward as forward, e.g., madam or nurses run.
'''
def palindrome(word):
    word=word.lower()
    rev=''
    for i in word:
        rev=i+rev
    if word==rev:
        return 'is palindrome'
    else:
        return 'is not palindrome'
palindrome('Madam')

'''
9. Write a Python program that accepts a hyphen-separated sequence of words as input and prints the words in a hyphen-separated sequence after sorting them alphabetically.
	Sample Items : green-red-yellow-black-white
	Expected Result : black-green-red-white-yellow
'''
#---using sorted() - return new sorted list
def sequence(s):
    l=s.split('-')
    sorts=sorted(l)
    new='-'.join(sorts)
    return new
s='green-red-yellow-black-white'
print(sequence(s))

#---using sort() - change original
def sequence(s):
    l=s.split('-')
    l.sort()
    new='-'.join(l)
    return new
s='green-red-yellow-black-white'
print(sequence(s))

'''
10. Write a Python program to detect the number of local variables declared in a function.
'''
def my_function():
    a = 10
    b = 20
    c = a + b
    d = "hello"
print("Number of local variables:", my_function.__code__.co_nlocals)

'''
11. Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument,
also create a lambda function that multiplies argument x with argument y and prints the result.
	Sample Output:
	25
	48
'''
add_15 = lambda x: x + 15
multiply = lambda x, y: x * y
print(add_15(10))
print(multiply(6, 8))

'''
12. Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.
	Sample Output:
	Double the number of 15 = 30
	Triple the number of 15 = 45
	Quadruple the number of 15 = 60
	Quintuple the number 15 = 75
'''
#using lambda func
def multiplier(n):
    return lambda x: x * n
double = multiplier(2)
triple = multiplier(3)
quadruple = multiplier(4)
quintuple = multiplier(5)
print("Double the number of 15 =", double(15))
print("Triple the number of 15 =", triple(15))
print("Quadruple the number of 15 =", quadruple(15))
print("Quintuple the number 15 =", quintuple(15))
print()

#---using nested func
def multiplier(n):
    def inner(x):
      return x*n
    return inner
print("Double the number of 15 =", multiplier(15)(2))
print("Triple the number of 15 =", multiplier(15)(3))
print("Quadruple the number of 15 =", multiplier(15)(4))
print("Quintuple the number 15 =", multiplier(15)(5))

'''
13. Write a Python program to sort a list of tuples using Lambda.
	Original list of tuples:
	[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
	Sorting the List of Tuples:
	[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]
'''
#*******************
l=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
s=sorted(l,key=lambda x: x[1])
print(s)

'''
14. Write a Python program to sort a list of dictionaries using Lambda.
	Original list of dictionaries :
	[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
	Sorting the List of dictionaries :
	[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}]
'''
#*******************
l=	[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
new=sorted(l,key=lambda x:x['color'])
print(new)

'''
15. Write a Python program to filter a list of integers using Lambda.
	Original list of integers:
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	Even numbers from the said list:
	[2, 4, 6, 8, 10]
	Odd numbers from the said list:
	[1, 3, 5, 7, 9]
'''
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even=list(filter(lambda x:x%2==0,l))
odd=list(filter(lambda x:x%2!=0,l))
print(even)
print(odd)

'''
16. Write a Python program to square and cube every number in a given list of integers using Lambda.
	Original list of integers:
	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	Square every number of the said list:
	[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
	Cube every number of the said list:
	[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
'''
l=	[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sq=list(map(lambda x:x**2,l))
cub=list(map(lambda x:x**3,l))
print(sq)
print(cub)

'''
18. Write a Python program to find if a given string starts with a given character using Lambda.
'''
starts_with = lambda s, ch: s.startswith(ch)
print(starts_with("Hello", "H"))
print(starts_with("Python", "p"))

'''
19. Write a Python program to rearrange positive and negative numbers in a given array using Lambda.
	Original arrays:
	[-1, 2, -3, 5, 7, 8, 9, -10]
	Rearrange positive and negative numbers of the said array:
	[2, 5, 7, 8, 9, -10, -3, -1]
'''
arr = [-1, 2, -3, 5, 7, 8, 9, -10]
pos = list(filter(lambda x: x > 0, arr))
neg = list(filter(lambda x: x < 0, arr))
neg.sort()
result = pos + neg
print(result)

'''
20. Write a Python program to count the even and odd numbers in a given array of integers using Lambda.
	Original arrays:
	[1, 2, 3, 5, 7, 8, 9, 10]
	Number of even numbers in the above array: 3
	Number of odd numbers in the above array: 5
'''
l=	[1, 2, 3, 5, 7, 8, 9, 10]
ecnt=len(list(filter(lambda x:x%2==0,l)))
ocnt=len(list(filter(lambda x:x%2!=0,l)))
print('Number of even numbers in the above array: ',ecnt)
print('Number of odd numbers in the above array: ',ocnt)

'''
21. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.
	Orginal list:
	[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
	Numbers of the above list divisible by nineteen or thirteen:
	[19, 65, 57, 39, 152, 190]
'''
#****
l=[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
d13_19=list(filter(lambda x:x%13==0 or x%19==0,l))
print(d13_19)

'''
22. Write a Python program to check whether a given string contains a capital letter, a lower case letter, a number and a minimum length using lambda.
'''
check_string = lambda s: (any(c.isupper() for c in s) and any(c.islower() for c in s) and any(c.isdigit() for c in s) and len(s) >= 8)
#any() is used to check if at least one element satisfies a condition
#Use any() in validation, searching, and checking conditions quickly
print(check_string("Hello123"))
print(check_string("hello123"))
print(check_string("HELLO123"))
print(check_string("Hello"))
print()

#---
check_string = lambda s: (len(list(filter(lambda c: c.isupper(), s))) > 0 and len(list(filter(lambda c: c.islower(), s))) > 0 and
    len(list(filter(lambda c: c.isdigit(), s))) > 0 and len(s) >= 8)
print(check_string("Hello123"))
print(check_string("hello123"))
print(check_string("HELLO123"))
print(check_string("Hello"))