# -*- coding: utf-8 -*-
"""OOP-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7fe9VDi6JfHmfPbue1et_xbIn3Z2wXw
"""

'''
1. Write a Python program to create a class representing a Circle. Include methods to calculate its area and perimeter.
'''
class circle:
  def __init__(self,radius):
    self.radius=radius
  def area(self): #pi*r^2
    return 3.14*self.radius*self.radius
  def perimeter(self): #2*pi*r
    return 2*3.14*self.radius
c=circle(4)
print("area of circle is: ",c.area())
print("perimeter of circle is: ",c.perimeter())

'''
2. Write a Python program to create a person class. Include attributes like name, country and date of birth. Implement a method to determine the person's age.
'''
from datetime import date
class Person:
  def __init__(self,name,country,dob):
    self.name=name
    self.country=country
    self.dob=dob
  def cal_age(self):
    today = date.today()
    age = today.year - self.dob.year
    return age
  def display(self):
        print("Name:", self.name)
        print("Country:", self.country)
        print("Date of Birth:", self.dob)
        print("Age:", self.cal_age())
p=Person('Raj','India',date(2003,3,11))
p.display()

'''
3. Write a Python program to create a calculator class. Include methods for basic arithmetic operations.
'''
class Calculator:
  def __init__(self,a,b):
    self.a=a
    self.b=b
  def add(self):
    return self.a+self.b
  def sub(self):
    return self.a-self.b
  def mul(self):
    return self.a*self.b
  def div(self):
    return self.a/self.b
c=Calculator(10,5)
print("Addition: ",c.add())
print("Subtraction: ",c.sub())
print("Multiplication: ",c.mul())
print("Division: ",c.div())

'''
4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter.
Implement subclasses for different shapes like circle, triangle, and square.
'''
'''4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter.
Implement subclasses for different shapes like circle, triangle, and square.'''
class Shape:
    def __init__(self,nm):
        self.nm=nm
    def area(self):
        pass
    def perimeter(self):
        pass
    def display(self):
        print('shape name:-',self.nm)
class Circle(Shape):
    def __init__(self,r):
        super().__init__('circle')
        self.r=r
    def area(self):
        return 3.14*self.r**2
    def perimeter(self):
        return 2*3.14*self.r
class Triangle(Shape):
    def __init__(self,a,b,c,h):
        super().__init__('triangle')
        self.a=a
        self.b=b
        self.c=c
        self.h=h
    def area(self):
        return 0.5*self.b*self.h
    def perimeter(self):
        return self.a+self.b+self.c
class Square(Shape):
    def __init__(self,a):
        super().__init__('square')
        self.a=a
    def area(self):
        return self.a*self.a
    def perimeter(self):
        return 4*self.a
c=Circle(3)
c.display()
print('area of circle:',c.area())
print('perimeter of circle:',c.perimeter(),'\n')
t=Triangle(3,4,5,4)
t.display()
print('area of triangle:',t.area())
print('perimeter of triangle:',t.perimeter(),'\n')
s=Square(2)
s.display()
print('area of square:',s.area())
print('perimeter of square:',s.perimeter())

'''
5. Write a Python program to create a class representing a binary search tree. Include methods for inserting and searching for elements in the binary tree.
'''
class Node:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None

class BinarySearchTree:
    def __init__(self):
        self.root = None
    def insert(self, key):
        if self.root is None:
            self.root = Node(key)     # First node becomes root
        else:
            current = self.root
            while True:
                if key < current.key:
                    if current.left is None:
                        current.left = Node(key)  # Insert on left
                        break
                    current = current.left
                elif key > current.key:
                    if current.right is None:
                        current.right = Node(key)  # Insert on right
                        break
                    current = current.right
                else:
                    break                    # key already exists, do nothing

    def search(self, key):
        current = self.root
        while current:
            if key == current.key:
                return True
            elif key < current.key:
                current = current.left
            else:
                current = current.right
        return False

bst = BinarySearchTree()
for i in [15, 10, 20, 8, 12, 17, 25]:
    bst.insert(i)
print("Searching for 12:", bst.search(12))  # True
print("Searching for 30:", bst.search(30))  # False

'''
6. Write a Python program to create a class representing a stack data structure. Include methods for pushing and popping elements.
'''
#*******************
class Stack:
    def __init__(self):
        self.stack = []
    def push(self, item):
        self.stack.append(item)
        print(f"Pushed: {item}")
    def pop(self):
        if not self.is_empty():
            removed = self.stack.pop()
            print(f"Popped: {removed}")
            return removed
        else:
            print("Stack is empty! Cannot pop.")
            return None
    def is_empty(self):
        return len(self.stack) == 0
    def display(self):
        print("Stack:", self.stack)
s = Stack()
s.push(10)
s.push(20)
s.push(30)
s.display()
s.pop()
s.display()
s.pop()
s.pop()
s.pop()

'''
7. Write a Python program to create a class representing a linked list data structure.
Include methods for displaying linked list data, inserting and deleting nodes.
'''
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = new_node
        print(f"Inserted: {data}")

    def delete(self, key):
        temp = self.head
        if temp and temp.data == key:
            self.head = temp.next
            print(f"Deleted: {key}")
            return
        prev = None
        while temp and temp.data != key:
            prev = temp
            temp = temp.next
        if temp is None:
            print("Value not found!")
            return
        prev.next = temp.next
        print(f"Deleted: {key}")

    def display(self):
        temp = self.head
        if temp is None:
            print("Linked List is empty")
            return
        print("Linked List:", end=" ")
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")
ll = LinkedList()

ll.insert(10)
ll.insert(20)
ll.insert(30)

ll.display()

ll.delete(20)
ll.display()

ll.delete(10)
ll.display()

'''
8. Write a Python program to create a class representing a shopping cart. Include methods for adding and removing items, and calculating the total price.
'''
class ShoppingCart:
    def __init__(self):
        self.items = []  # list of tuples: (name, price)

    def add_item(self, name, price, qty):
      self.items.append((name, price, qty))
      print(f"{name} added to the cart:- ",end='')
      print(self.items)

    def remove_item(self, name):
        for i, (n, p, q) in enumerate(self.items):
            if n == name:
                self.items.pop(i)
                print(f"{name} removed from the cart.")
                return
        print(f"{name} not found in the cart.")

    def total_price(self):
        total = 0
        for name, price, qty in self.items:
            total = total + price * qty
        return total

    def display_cart(self):
        if not self.items:
            print("Cart is empty.")
        else:
            print("Items in Cart:")
            for name, price, qty in self.items:
                print(f"{name} - Rs.{price} - Qty.{qty}")
            print(f"Total Price: Rs.{self.total_price()}")
cart = ShoppingCart()
cart.add_item("Pen", 5, 10)
cart.add_item("Notebook", 40, 5)
cart.add_item("Compass", 200, 2)
print()
cart.display_cart()
print()
cart.remove_item("Apple")
cart.display_cart()

'''
9. Write a Python program to create a class representing a stack data structure. Include methods for pushing, popping and displaying elements.
'''
#*******************
class stack:
    def __init__(self):
        self.st=[]

    def push(self,n):
        self.st.append(n)
        print(f'Pushed:{n}')

    def pop(self):
        if len(self.st)==0:
            print('---Stack is empty. Cannot pop.')
            return None
        else:
            remove=self.st.pop()
            print(f'Popped:{remove}')
            return remove

    def display(self):
        print('Stack:',self.st)
s=stack()
s.push(4)
s.push(5)
s.push(6)
s.display()
s.pop()
s.display()
s.pop()
s.pop()
s.pop()

'''
10. Write a Python program to create a class representing a queue data structure. Include methods for enqueueing and dequeueing elements.
'''
#*******************
class Queue:
    def __init__(self):
        self.que=[]
    def enqueue(self,n):
        self.que.append(n)
        print(f'Enqueued:{n}')
    def dequeue(self):
        if len(self.que)==0:
            print('---Queue is empty. Cannot dequeue.')
            return None
        else:
            remove=self.que.pop(0)
            print(f'Dequeued:{remove}')
            return remove
    def display(self):
        print('Queue:',self.que)
q=Queue()
q.enqueue(4)
q.enqueue(5)
q.enqueue(6)
q.display()
q.dequeue()
q.display()
q.dequeue()
q.dequeue()
q.dequeue()
print()

#---using module
from collections import deque
class Queue:
    def __init__(self):
        self.que = deque()
    def enqueue(self, n):
        self.que.append(n)
        print(f'Enqueued: {n}')
    def dequeue(self):
        if len(self.que) == 0:
            print('---Queue is empty. Cannot dequeue.')
            return None
        else:
            remove = self.que.popleft()
            print(f'Dequeued: {remove}')
            return remove
    def display(self):
        print('Queue:', list(self.que))
q = Queue()
q.enqueue(4)
q.enqueue(5)
q.enqueue(6)
q.display()
q.dequeue()
q.display()
q.dequeue()
q.dequeue()
q.dequeue()

'''
11. Write a Python program to create a class representing a bank. Include methods for managing customer accounts and transactions.
	Create a Python class called BankAccount which represents a bank account, having as attributes: accountNumber (numeric type), name (name of the account owner as string type), balance.
	Create a constructor with parameters: accountNumber, name, balance.
	Create a Deposit() method which manages the deposit actions.
	Create a Withdrawal() method which manages withdrawals actions.
	Create an bankFees() method to apply the bank fees with a percentage of 5% of the balance account.
	Create a display() method to display account details. Give the complete code for the BankAccount class.
'''
class BankAccount:
    def __init__(self,acc_no: int,nm: str,bal):
        self.acc_no=acc_no
        self.nm=nm
        self.bal=bal
    def deposit(self,amt):
        self.amt=amt
        self.bal+=self.amt
        print(f'\nRs.{self.amt} deposit Successfully! Total Amount:{self.bal}')
    def withdraw(self,amt):
        self.amt=amt
        if amt > self.bal:
            print(f"\nInsufficient balance! Cannot withdraw Rs.{amt}")
        else:
            self.bal-=self.amt
            print(f'Rs.{self.amt} withdraw Successfully! Remaining amt:{self.bal}')
    def bankfees(self):
        fee=self.bal*0.05
        self.bal-=fee
        print(f"\n---Bank fees of Rs.{fee:.2f} applied. Remaining Balance: Rs.{self.bal}---")

    def display(self):
      print('Account no:',self.acc_no)
      print('Name:',self.nm)
      print(f'Current Balance:{self.bal:.2f}')
b=BankAccount(1001,'rohan',20000)
b1=BankAccount(1002,'Moham',30000)

b.deposit(5000)
b.withdraw(10000)
b.bankfees()
b.display()

b1.deposit(4000)
b1.withdraw(20000)
b1.bankfees()
b1.display()

'''
12. Build a flashcard using class in python. A flashcard is a card having information on both sides,
  which can be used as an aid in memoization. Flashcards usually have a question on one side and an answer on the other.
	Example 1:
	Approach:
	Create a class named FlashCard.
	Initialize dictionary fruits using init() method. Here you have to define fruit name as key and it's color as value.
  E.g., {"Banana": "yellow", "Strawberries": "pink"}
	Now randomly choose a pair from fruits by using random module and store the key in variable fruit and value in variable color.
	Now prompt the user to answer the color of the randomly chosen fruit.
	If correct print correct else print wrong.
	Output:
	welcome to fruit quiz
	What is the color of Strawberries
	pink
	Correct answer
	Enter 0, if you want to play again: 0
	What is the color of watermelon
	green
	Correct answer
	Enter 0, if you want to play again: 1
'''
#*******************
import random
class FlashCard:
    def __init__(self):
        self.fruits = {
            "Banana": "yellow",
            "Strawberries": "pink",
            "Watermelon": "green",
            "Apple": "red"
        }

    def tell(self):
        print('---welcome to fruit quiz---')
        while True:
            fruit, color = random.choice(list(self.fruits.items()))
            c=input(f'what is the color of {fruit}? ')
            if c.lower()==color:
                print('--correct answer')
            else:
                print('--wrong answer--')
            no=int(input('\nEnter 0, if you want to play again:'))
            if no!=0:
                print('Thanks for playing!')
                break
f=FlashCard()
f.tell()

'''
13. TechWorld, a technology training center, wants to allocate courses for instructors. An instructor is identified by name, technology skills, experience and average feedback. An instructor is allocated a course, if he/she satisfies the below two conditions:

	eligibility criteria:
	if experience is more than 3 years, average feedback should be 4.5 or more
	if experience is 3 years or less, average feedback should be 4 or more
	he/she should posses the technology skill for the course
	Identify the class name and attributes to represent instructors. Write a Python program to implement the class chosen with its attributes and methods.

	Note:

	Consider all instance variables to be private and methods to be public.
	An instructor may have multiple technology skills, so consider instance variable, technology_skill to be a list.
	check_eligibility(): Return true if eligibility criteria is satisfied by the instructor. Else, return false
	allocate_course(technology): Return true if the course which requires the given technology can be allocated to the instructor. Else, return false.
	Represent a few objects of the class, initialize instance variables using setter methods, invoke appropriate methods and test your program.

'''
#*******************
class Instructor:
    def __init__(self):
        self.__name=None
        self.__tech_skill=[]
        self.__experience=None
        self.__feedback=None
    def set_name(self,name):
        self.__name=name
    def set_technology_skill(self,tech_skill):
        self.__tech_skill=tech_skill
    def set_experience(self,experience):
        self.__experience=experience
    def set_average_feedback(self,feedback):
        self.__feedback=feedback
    def check_eligibility(self):
        if self.__experience>3:
            return self.__feedback>=4.5
        else:
            return self.__feedback>=4
    def allocate_course(self,technology):
        if self.check_eligibility() is True and technology in self.__tech_skill:
            return True
        else:
            return False
ins=Instructor()
ins.set_name('Mohan')
ins.set_technology_skill(["Python", "Java"])
ins.set_experience(6)
ins.set_average_feedback(4.7)
print("Eligible:", ins.check_eligibility())
print("Course Allocation (Python):", ins.allocate_course("Python"))

'''
14. Write a program that uses datetime module within a class. Enter manufacturing date and expiry date of the product. The program must display the years, months and days that are left for expiry.
'''
from datetime import date
class Product:
    def __init__(self,mdate,edate):
        self.mdate=mdate
        self.edate=edate
    def display(self):
        today=date.today()
        years=self.edate.year-today.year
        months=self.edate.month-today.month
        days=self.edate.day-today.day
        print('year: ',years)
        print('months: ',months)
        print('days: ',days)
p=Product(date(2023,1,1), date(2026,12,31))
p.display()

'''
15. A university wants to automate their admission process. Students are admitted based on the marks scored in the qualifying exam.
 A student is identified by student id, age and marks in qualifying exam. Data are valid, if:
	Age is greater than 20
	Marks is between 0 and 100 (both inclusive)
	A student qualifies for admission, if
	Age and marks are valid and
	Marks is 65 or more
	Write a python program to represent the students seeking admission in the university.
'''
class Admission:
    def __init__(self,sid,age,marks):
        self.sid=sid
        self.age=age
        self.marks=marks
    def is_valid(self):
        if self.age > 20 and 0 <= self.marks <= 100:
            return True
        else:
            return False
    def is_eligible(self):
        if self.is_valid() and self.marks >= 65:
            return True
        else:
            return False
    def display(self):
        if self.is_eligible():
            print('Student is admitted..!')
        else:
            print('Student is not admitted..!')
a=Admission(101,22,80)
a.display()

'''
16. Ice-Cream Scoops and Bowl shop
	Create a class Scoop which has one public property flavor and one private proptery price. Take flavor values during object creation.
	Create a class Bowl with private prperty scoop_list which will have list of scoopd object.
	Create a method add_scoops in Bowl class which will add any no of Scoop objects given as parameter and store it in scoops_list.
	Make getter and setter method for price property.
	Make a method display to display flavour and price of each Scoop in scoop_list and
  print total price of the bowl by adding all flavour scoops prices.
	Make a method sold in both Scoop class and Bowl class to print no of quantity sold.
'''
#*******************
class Scoop:
    count = 0
    def __init__(self, flavor):
        self.flavor = flavor
        self.__price = 0
        Scoop.count += 1
    def set_price(self, price):
        self.__price = price
    def get_price(self):
        return self.__price
    def sold(self):
        print("Total scoops sold:", Scoop.count)
class Bowl:
    count = 0
    def __init__(self):
        self.__scoop_list = []
        Bowl.count += 1
    def add_scoops(self, *scoops):
        for scoop in scoops:
            self.__scoop_list.append(scoop)
    def display(self):
        total = 0
        print("\nScoops in Bowl:")
        for scoop in self.__scoop_list:
            print("Flavor:", scoop.flavor, "| Price:", scoop.get_price())
            total += scoop.get_price()
        print("Total Price of Bowl:", total)
    def sold(self):
        print("Total bowls sold:", Bowl.count)
s1 = Scoop("Chocolate")
s1.set_price(50)
s2 = Scoop("Vanilla")
s2.set_price(40)
s3 = Scoop("Strawberry")
s3.set_price(60)
b = Bowl()
b.add_scoops(s1, s2, s3)
b.display()
s1.sold()
b.sold()

'''
17. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100.
If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge.
So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

Note: The bus seating capacity is 50. so the final fare amount should be 5500.
You need to override the fare() method of a Vehicle class in Bus class.
'''
class Vehicle:
    def __init__(self,seating_capacity):
        self.seating_capacity=seating_capacity
    def fare(self):
        return self.seating_capacity*100
class Bus(Vehicle):
    def fare(self):
        base_fare=super().fare()
        base_amt=base_fare*0.1
        total_fare=base_fare+base_amt
        return total_fare
b=Bus(50)
print(b.fare())

'''18. Write a Python class Employee with attributes like emp_id, emp_name, emp_salary, and emp_department and methods like calculate_emp_salary, emp_assign_department, and print_employee_details.

	Sample Employee Data:
	"ADAMS", "E7876", 50000, "ACCOUNTING"
	"JONES", "E7499", 45000, "RESEARCH"
	"MARTIN", "E7900", 50000, "SALES"
	"SMITH", "E7698", 55000, "OPERATIONS"

	Use 'assign_department' method to change the department of an employee.
	Use 'print_employee_details' method to print the details of an employee.
	Use 'calculate_emp_salary' method takes two arguments: salary and hours_worked, which is the number of hours worked by the employee. If the number of hours worked is more than 50, the method computes overtime and adds it to the salary. Overtime is calculated as following formula:
	overtime = hours_worked - 50
	Overtime amount = (overtime * (salary / 50))
'''
class Employee:
    def __init__(self,nm,eid,sal,dept):
        self.nm=nm
        self.eid=eid
        self.sal=sal
        self.dept=dept
    def cal_sal(self,hrs):
        if hrs>50:
            overtime = hrs - 50
            overtime_amount = (overtime * (self.sal / 50))
            self.sal += overtime_amount
            print(f"Added ₹{overtime_amount:.2f} in overtime pay.")
        return self.sal
    def emp_assign_dept(self,dept):
        self.dept=dept
    def emp_details(self):
        print(f"Name: {self.nm}")
        print(f"Employee ID: {self.eid}")
        print(f"Salary: ₹{self.sal:,.2f}")
        print(f"Department: {self.dept}\n")

employees = [
    Employee("ADAMS", "E7876", 50000, "ACCOUNTING"),
    Employee("JONES", "E7499", 45000, "RESEARCH"),
    Employee("MARTIN", "E7900", 50000, "SALES"),
    Employee("SMITH", "E7698", 55000, "OPERATIONS")
]
print("---Initial Employee Details---\n")
for emp in employees:
    emp.emp_details()

print("\nUpdating JONES' department to SALES:")
employees[1].emp_assign_dept("SALES")
employees[1].emp_details()

print("\nCalculating SMITH's salary with 60 hours worked:")
smith = employees[3]
smith.cal_sal(60)
smith.emp_details()

print("Updated Employee Details:")
for emp in employees:
    emp.emp_details()

'''
19. Write a Python class Restaurant with attributes like menu_items, book_table, and customer_orders, and methods like add_item_to_menu, book_tables, and customer_order.

	Perform the following tasks now:

	Now add items to the menu.
	Make table reservations.
	Take customer orders.
	Print the menu.
	Print table reservations.
	Print customer orders.
	Note: Use dictionaries and lists to store the data.
'''
#*******************
class Restaurant:
    def __init__(self):
        self.menu_items = {}
        self.book_table = []
        self.customer_orders = []
    def add_item_to_menu(self, name, price):
        self.menu_items[name] = price
    def book_tables(self, name):
        self.book_table.append(name)
    def customer_order(self, name, item):
        self.customer_orders.append((name, item))
    def print_menu(self):
        print("\nMenu:")
        for item, price in self.menu_items.items():
            print(item, ":", price)
    def print_tables(self):
        print("\nTable Reservations:")
        for name in self.book_table:
            print(name)
    def print_orders(self):
        print("\nCustomer Orders:")
        for name, item in self.customer_orders:
            print(name, "ordered", item)
r = Restaurant()
r.add_item_to_menu("Pizza", 200)
r.add_item_to_menu("Burger", 100)
r.book_tables("Rohan")
r.book_tables("Amit")
r.customer_order("Rohan", "Pizza")
r.customer_order("Amit", "Burger")
r.print_menu()
r.print_tables()
r.print_orders()

'''
20. Write a Python class BankAccount with attributes like account_number, balance, date_of_opening and customer_name, and
methods like deposit, withdraw, and check_balance.
'''
class BankAccount:
    def __init__(self,acc_no,nm,bal,odate):
        self.acc_no=acc_no
        self.nm=nm
        self.bal=bal
        self.odate=odate
    def deposit(self,amt):
        self.amt=amt
        self.bal+=self.amt
        print(f'\nRs.{self.amt} deposit Successfully! Total Amount:{self.bal}')
    def withdraw(self,amt):
        self.amt=amt
        if amt > self.bal:
            print(f"\nInsufficient balance! Cannot withdraw Rs.{amt}")
        else:
            self.bal-=self.amt
            print(f'Rs.{self.amt} withdraw Successfully! Remaining amt:{self.bal}')
    def display(self):
      print('Account no:',self.acc_no)
      print('Name:',self.nm)
      print(f'Current Balance:{self.bal:.2f}')
      print(f'Date_of_opening:{self.odate}')
b=BankAccount(1001,'rohan',20000,'11-4-2003')
b1=BankAccount(1002,'Moham',30000,'13-8-2005')

b.deposit(5000)
b.withdraw(10000)
b.display()

b1.deposit(4000)
b1.withdraw(20000)
b1.display()

'''
21. Write a Python class Inventory with attributes like item_id, item_name, stock_count, and price,
and methods like add_item, update_item, and check_item_details.
'''
#*******************
class Inventory:
    def __init__(self, item_id, item_name, stock_count, price):
        self.item_id = item_id
        self.item_name = item_name
        self.stock_count = stock_count
        self.price = price
    def add_item(self):
        print("Item added successfully!")
    def update_item(self, name=None, stock=None, price=None):
        if name:
            self.item_name = name
        if stock:
            self.stock_count = stock
        if price:
            self.price = price
        print("Item updated successfully!")
    def check_item_details(self):
        print("Item Details:")
        print("Item ID:", self.item_id)
        print("Item Name:", self.item_name)
        print("Stock Count:", self.stock_count)
        print("Price:", self.price,'\n')
i = Inventory(1, 'Pen', 50, 5)
i.add_item()
i.check_item_details()
i.update_item(name='Pencil', stock=100, price=10)
i.check_item_details()