# -*- coding: utf-8 -*-
"""Hospital Patient Queue Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BKGuFEsmkGCNb8ho9DkxoQErb0WK_IZ

**Hospital Patient Queue Management System**

The Hospital Patient Queue Management System is a Python-based command-line application designed to manage patient queues in a hospital.
It utilizes object-oriented programming (OOP) principles and includes three main classes: Patient, Specialization, and OperationsManager. This project provides a simple yet effective way to handle patient data and queue management within a hospital setting.

The Hospital Patient Queue Management System is an illustration of OOP concepts in Python. It consists of three primary classes, each serving a specific purpose:

**Patient:**

The Patient class represents an individual patient and includes the following attributes:

*	name: The name of the patient.
*	status: The patient's status, which can be 0 (normal), 1 (urgent), or 2 (super-urgent).

This class provides methods for string representation and status formatting for patients.

**Specialization:**

The Specialization class manages patient queues within different specializations. It offers functionalities such as:

*	Adding patients with various urgency levels.
*	Retrieving the next patient from the queue.
*	Removing patients by name.
*	Checking queue capacity.

**OperationsManager:**
The OperationsManager class serves as the user interface for interacting with the Specialization instances. Users can perform actions like:

*	Adding new patients to specializations.
*	Listing patients in specializations.
*	Retrieving the next patient.
*	Removing patients.
*	Ending the program gracefully.
"""

class Patient:
  def __init__(self, name, status):
    self.name = name
    self.status = status

  def __str__(self):
        return f"Name: {self.name}, Status: {self.status}"

p = Patient("Raj", 2)  #p = Patient(name="Raj", status=2) think like this
print(p)                         #inside a obj - p.name = "Raj", emp.status = 2

from tabulate import tabulate

class Specialization:
  def __init__(self):
    self.queue = []

  def add_patient(self, name, status):
      p = Patient(name, status)
      if p.status == 0:
          self.queue.insert(0, p)
      elif p.status == 1:
          for i, patient in enumerate(self.queue):
              if patient.status == 2:
                  self.queue.insert(i, p)
                  return
          self.queue.append(p)
      if p.status == 2:
          self.queue.append(p)


  def list_patients(self):
    if not self.queue:
        print("No patient found.")
        return #return immediately exits the method.
    table = []
    for p in self.queue: # p = actual patient object
        table.append([p.name, p.status])
    print("\n======= Patient List =======\n")
    print(tabulate(table, headers=["Name", "Status"], tablefmt="grid"))
    print('Patients listed successfully...!')

  def get_next_patient(self):
    if not self.queue:
        print("No patients in queue.")
        return
    patient = self.queue.pop(0)
    print(f"Next patient: {patient.name}")
    print('Retrieved successfully...!')

  def remove_patient(self, name):
    for i in range(len(self.queue)):
      if self.queue[i].name.lower() == name.lower():
        self.queue.pop(i)
        print('Patient removed successfully...!')
        return

  def check_queue_capacity(self):
      print('Queue capacity:', len(self.queue))
      return len(self.queue)

s=Specialization()
s.add_patient('John', 0)
s.add_patient('Jane', 1)
s.add_patient('Bob', 2)
s.add_patient('Alice', 0)
s.add_patient('Eve', 1)
s.list_patients()
s.get_next_patient()
s.remove_patient('Jane')
s.check_queue_capacity()

class OperationsManager:
  def __init__(self):
    self.s=Specialization()
    self.menu()

  def menu(self):
    while True:
      print('\n______ Patient Menu ______')
      print('1. Add patient')
      print('2. List patients')
      print('3. Get next patient')
      print('4. Remove patient')
      print('5. Exit')

      try:
        choice = int(input('Enter your choice: '))
      except ValueError:
        print('Invalid input. Please enter a number.')
        continue


      if choice == 1:
        self.add_patient()
      elif choice == 2:
        self.list_patients()
      elif choice == 3:
        self.get_next_patient()
      elif choice == 4:
        self.remove_patient()
      elif choice == 5:
        self.exiting()
        break
      else:
        print('Invalid choice. Please try again.')

  def add_patient(self):
    try:
      no=int(input('How many patients to add:'))
    except ValueError:
      print('Invalid input!')

    for i in range(no):
      print(f'\n----Enter details of patient {i+1}----')
      name = input('Enter patient name: ')

      try:
        status = int(input('Enter patient status (0 for normal) 0-2: '))
      except ValueError:
        print('Invalid input!')
        continue

      self.s.add_patient(name,status)
      print('Patient added successfully...!')
    self.menu()

  def list_patients(self):
    self.s.list_patients()
    self.menu()

  def get_next_patient(self):
    self.s.get_next_patient()
    self.menu()

  def remove_patient(self):
    name = input('Enter patient name: ')
    self.s.remove_patient(name)
    self.menu()

  def check_queue_capacity(self):
    self.s.check_queue_capacity()
    self.menu()

  def exiting(self):
      print('Thank you for using the Operations Manager!')
      exit()

om=OperationsManager()